import type { ImageSourcePropType } from 'react-native';

/**
 * AUTO-GENERATED by tools/generateAssetRegistry.mjs from
 * src/data/db/assetRegistry.config.json
 */
export const IMAGE_REGISTRY = {
  'image.bird.remote': { uri: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=300&q=60' },
  'image.cat.local': require('../../../assets/images/cat.png'),
  'image.farewell.remote': { uri: 'https://images.unsplash.com/photo-1464375117522-1311d6a5b81d?auto=format&fit=crop&w=300&q=60' },
  'image.greeting.remote': { uri: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=300&q=60' },
  'image.octopus.local': require('../../../assets/images/octopus.png'),
  'image.star.local': require('../../../assets/images/star.png'),
} as const;

export const AUDIO_REGISTRY = {
  'audio.enoho.local': require('../../../assets/audio/e-noho-ra.mp3'),
  'audio.whetu.local': require('../../../assets/audio/whetu.mp3'),
} as const;

export const resolveImageFromKey = (assetKey?: string): ImageSourcePropType | undefined => {
  if (!assetKey) {
    return undefined;
  }
  return IMAGE_REGISTRY[assetKey as keyof typeof IMAGE_REGISTRY];
};

export const resolveAudioFromKey = (assetKey?: string): number | { uri: string } | undefined => {
  if (!assetKey) {
    return undefined;
  }
  return AUDIO_REGISTRY[assetKey as keyof typeof AUDIO_REGISTRY];
};
