import fs from 'node:fs';
import path from 'node:path';

const configPath = path.resolve(process.cwd(), 'src', 'data', 'db', 'assetRegistry.config.json');
const outputPath = path.resolve(process.cwd(), 'src', 'data', 'db', 'assetRegistry.ts');

const raw = fs.readFileSync(configPath, 'utf8');
const config = JSON.parse(raw);

const sortEntries = (obj) =>
  Object.entries(obj ?? {}).sort(([a], [b]) => a.localeCompare(b));

const renderSource = (source) => {
  if (source?.requirePath) {
    return `require('${source.requirePath}')`;
  }
  if (source?.uri) {
    return `{ uri: '${source.uri}' }`;
  }
  throw new Error(`Invalid asset source: ${JSON.stringify(source)}`);
};

const renderRegistry = (title, entries) => {
  const rows = entries.map(([key, source]) => `  '${key}': ${renderSource(source)},`);
  return `export const ${title} = {\n${rows.join('\n')}\n} as const;\n`;
};

const imageEntries = sortEntries(config.images);
const audioEntries = sortEntries(config.audio);

const file = `import type { ImageSourcePropType } from 'react-native';

/**
 * AUTO-GENERATED by tools/generateAssetRegistry.mjs from
 * src/data/db/assetRegistry.config.json
 */
${renderRegistry('IMAGE_REGISTRY', imageEntries)}
${renderRegistry('AUDIO_REGISTRY', audioEntries)}
export const resolveImageFromKey = (assetKey?: string): ImageSourcePropType | undefined => {
  if (!assetKey) {
    return undefined;
  }
  return IMAGE_REGISTRY[assetKey as keyof typeof IMAGE_REGISTRY];
};

export const resolveAudioFromKey = (assetKey?: string): number | { uri: string } | undefined => {
  if (!assetKey) {
    return undefined;
  }
  return AUDIO_REGISTRY[assetKey as keyof typeof AUDIO_REGISTRY];
};
`;

fs.writeFileSync(outputPath, file);
console.log(`Asset registry generated: ${outputPath}`);
